sudo: false
language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - 3.6

install:
  - pip install pipenv
  - pipenv install

script:
  - python setup.py install
  - pytest -v tests/
